FROM eclipse-temurin:21-jre-alpine
WORKDIR /opt/app
EXPOSE 8080
EXPOSE 5005

RUN mkdir -p /etc/hlabmonitor /var/lib/hlabmonitor /var/log/hlabmonitor && \
    chown -R 1001:1001 /etc/hlabmonitor /var/lib/hlabmonitor /var/log/hlabmonitor

COPY target/*.jar /opt/app/app.jar
COPY docker/entrypoint.sh /opt/app/entrypoint.sh

RUN chmod +x /opt/app/entrypoint.sh

ENV HLABMONITOR_CONFIG_LOCATION=""
ENV DEBUG_MODE="false"

USER 1001:1001

ENTRYPOINT ["/opt/app/entrypoint.sh"]